### ISSUE TITLE
[Feature Request] Scroll back to top button 

### ISSUE THREAD

**Issue by Angeltheesoto** [BeforeIDieCode/BeforeIDieAchievements#141]
## Feature:
We could create a button that appears into view when the user reaches a certain point down the page. When the user clicks the button it will make the page scroll back to the top. This will let the user quickly go back to the top of the page without having to manually scroll.

## Possible solutions:
Create a button tag with an onClick that takes in a "scrollToTop" function. Inside the scrollToTop function, defined in app.js, you can use the following:
```
window.scrollTo({ top: 0, behavior: smooth })
```
this will scroll the user back to the top.

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [X] I am willing to work on this issue (optional)

**Comment by XanderRubio** [comment]
Hi @Angeltheesoto,

That's a fantastic idea! You should definitely execute it, as it would make for a great user experience feature. The random generator component is still present in the main branch code. However, I have removed the element for rendering as it was distracting on the new header. One would need to adjust the CSS margins to ensure it is set in an area that isn't distracting. If you want, you can also add the random Contributor render so that it shows up better on the new header since you're familiar with the code now (if you would like). Happy hacking, and the feature branch `feature-scroll` has been added to work on now.

**Comment by Angeltheesoto** [comment]
Thank you @XanderRubio, and I'll start working on it today.

**Comment by XanderRubio** [comment]
> Thank you @XanderRubio, and I'll start working on it today.

Great!

**Comment by XanderRubio** [comment]
Successfully implemented in pull request #148
